species_names = [
"Acrocomia aculeata",
"Allium sativum",
"Allium schoenoprasum",
"Anacardium occidentale",
"Ananas comosus",
"Annona muricata",
"Annona squamosa",
"Arachis hypogaea",
"Astrocaryum murumuru",
"Attalea speciosa",
"Avena byzantina",
"Avena sativa",
"Brassica napus",
"Byrsonima crassifolia",
"Capsicum",
"Carapa guianensis",
"Carica papaya",
"Caryocar brasiliense",
"Citrullus lanatus",
"Citrus aurantiifolia",
"Citrus limon",
"Citrus reticulata",
"Citrus sinensis",
"Coffea arabica",
"Coffea canephora",
"Colocasia esculenta",
"Coriandrum sativum",
"Cucumis melo",
"Cucurbita maxima",
"Daucus carota",
"Dimorphandra mollis",
"Dipteryx odorata",
"Euterpe edulis", # Duplicate, Euterpe oleracea is the correct name for Acai-verdadeiro
"Euterpe oleracea",
"Genipa americana",
"Glycine max",
"Gossypium",
"Hancornia speciosa",
"Helianthus annuus",
"Hordeum vulgare",
"Ipomoea batatas",
"Lactuca sativa",
"Malpighia glabra",
"Malus domestica",
"Mangifera indica",
"Mauritia flexuosa",
"Musa acuminata",
"Musa balbisiana",
"Oryza glaberrima",
"Oryza sativa",
"Passiflora edulis",
"Pennisetum glaucum",
"Petroselinum crispum",
"Phaseolus vulgaris",
"Piper nigrum",
"Prunus persica",
"Psidium guajava",
"Ricinus communis",
"Saccharum",
"Secale cereale",
"Solanum melongena",
"Solanum tuberosum",
"Sorghum bicolor",
"Spondias mombin",
"Spondias purpurea",
"Spondias tuberosa",
"Syagrus coronata",
"Tamarindus indica",
"Theobroma cacao",
"Theobroma grandiflorum",
"Triticum x Secale", # Corrected to represent the hybrid nature
"Triticum",
"Vicia faba",
"Vitis vinifera",
"Zea mays"
]
